### PR TITLE
Add a new version in language

### PR DESCRIPTION
**Pull request by preytaren**
i've translated index.html into simplified chinese, I think a new branch should be opened to maintain these changes, but i can't do that, so i opened this pull request.

### CODE REVIEW

**Comment by llimllib** [comment]
wow, awesome! I'll pull it into master. Would you like me to make you a contributor so you can make fixes to it as necessary?

**Comment by preytaren** [comment]
that would be nice，and i think maybe you should copy the js file into the zhCN folder ，so that they could open the html directly.

**Comment by llimllib** [comment]
Sure, I added you as a contributor, feel free to move that around

**Comment by preytaren** [comment]
I found your updated webpage contains some places still remain untranslated，but my fork is 3 commit behind yours, i don't know how to make these modifications

**Comment by llimllib** [comment]
I think the easiest way will be to just update `/zh_CN/index.html` as you translate additional segments

**Pull request closed without merging**
